### ISSUE TITLE
error: Cannot instantiate interface Psr\Http\Client\ClientInterface

### ISSUE THREAD

**Issue by Snowbaha** [Meteo-Concept/hcaptcha-bundle#8]
Hello, I am on symfony 3.4, with php 7.4. 
I followed the install guide but when I valided the form with hCaptcha confirmed, I have this error and I don't know how to do to debug this.
Any idea?

```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Cannot instantiate interface Psr\Http\Client\ClientInterface" at /home/www/site/var/cache/prod/ContainerQuncj5h/getMeteoConceptHCaptcha_CaptchaVerifierService.php line 8 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot instantiate interface Psr\\Http\\Client\\ClientInterface at /home/www/site/var/cache/prod/ContainerQuncj5h/getMeteoConceptHCaptcha_CaptchaVerifierService.php:8)"} []
```

Let me know if you need more informations! :)

**Comment by lgeorget** [comment]
Hello!
Thank you for your bug report.
Do you have a specific configuration for GuzzleHttp (in config/packages/...)?

**Comment by Snowbaha** [comment]
Nothing speciale in config.yaml but I added this to my services.yaml :
![image](https://user-images.githubusercontent.com/3284722/144422068-55bc8ad1-4c67-4f45-b079-f3834fd5ab75.png)

**Comment by lgeorget** [comment]
Unless I'm misunderstanding your config, that won't work, these are interfaces, not classes, so you cannot use them after "class: " because they're not instantiable. You have to use GuzzleHttp / Nyholm Psr7 classes. Normally you don't need those lines at all in services.yaml, the bundles should have the services ready.

**Comment by Snowbaha** [comment]
Ok maybe I am wrong womewhere but without theses lines, I have this error:
![image](https://user-images.githubusercontent.com/3284722/144424809-0d33d740-7313-46b6-b37d-926a68d9d293.png)

**Comment by lgeorget** [comment]
Ah, so you do need to configure explicitly the classes that satisfy the interfaces then. f you use Guzzle, you can user:
```yaml
services:
    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client
    Psr\Http\Message\RequestFactoryInterface:
        class: Nyholm\Psr7\Factory\Psr17Factory
    Psr\Http\Message\StreamFactoryInterface:
        class: Nyholm\Psr7\Factory\Psr17Factory
```
